	</div>
	<div id='footer'>
		<div class='csh'><a href="http://www.csh.rit.edu/"><img src="./img/csh.png" alt="CSH" /></a></div>
		<a href='status.php'>Status</a> | <a href='http://github.com/benrr101/schedulemaker'>Report Issues</a>
		<div>
			Idea: John Resig (phytar at csh.rit.edu)<br />
			Development: Ben Russell (benrr101 at csh.rit.edu), Ben Grawi (bgrawi at csh.rit.edu)<br />
			Hosting: <a href="http://www.csh.rit.edu/">Computer Science House</a><br />
			Uses <a href="http://somerandomdude.com/work/iconic/">iconic icon set by P.J. Onori</a>, 
			licensed under <a href="http://creativecommons.org/licenses/by-sa/3.0/us/">CC BY-SA 3.0</a>
		</div>
	</div>
	</div>
	</body>
</html>
