	</div>
	<div id='footer'>
		<h2><a href='index.php'>ScheduleMaker</a></h2>
		<p><a href='generate.php'>Build Schedules</a> | <a href='browse.php'>Browse Courses</a> | <a href='roulette.php'>Course Roulette</a> | <a href='status.php'>Status</a></p>
		<p>Idea by: John Resig (phytar at csh.rit.edu) | Developed by: Ben Russell (benrr101 at csh.rit.edu) | Hosted by: <a href='http://www.csh.rit.edu/'>Computer Science House</a></p>
	</div>
	<script type='text/javascript>
		document.title = "<?= isset($TITLE) ? $TITLE : "ScheduleMaker" ?>";
	</script>
	</body>
</html>
